/**
 * Mock Data for Development
 * This file contains mock data that mirrors the backend structure
 */

import type {
  ApplicationUser,
  DoctorProfileViewModel,
  AppointmentItemViewModel,
  ConsultationViewModel,
  PredictionResultViewModel,
  SystemStatistics,
  DoctorApprovalViewModel,
  PatientProfileSummaryViewModel,
} from "@/types/backend-types"

// ===== MOCK USERS =====
export const mockUsers: ApplicationUser[] = [
  {
    id: "patient-123",
    userName: "john.doe@email.com",
    email: "john.doe@email.com",
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1985-05-15",
    gender: 1, // Male
    phoneNumber: "+1234567890",
    address: "123 Main St, New York, NY 10001",
    profilePicture: undefined,
    role: { id: "role-patient", name: "Patient" },
    isActive: true,
    createdAt: "2024-01-15T10:00:00Z",
    lastLoginAt: "2024-12-13T08:00:00Z",
  },
  {
    id: "doctor-456",
    userName: "dr.smith@email.com",
    email: "dr.smith@email.com",
    firstName: "Sarah",
    lastName: "Smith",
    dateOfBirth: "1978-03-20",
    gender: 2, // Female
    phoneNumber: "+1987654321",
    address: "456 Medical Plaza, Boston, MA 02101",
    profilePicture: undefined,
    role: { id: "role-doctor", name: "Doctor" },
    isActive: true,
    createdAt: "2024-01-10T10:00:00Z",
    lastLoginAt: "2024-12-13T07:30:00Z",
  },
  {
    id: "admin-789",
    userName: "admin@medipredict.com",
    email: "admin@medipredict.com",
    firstName: "Admin",
    lastName: "User",
    dateOfBirth: "1980-01-01",
    gender: 1,
    phoneNumber: "+1122334455",
    address: "789 Admin Tower, Chicago, IL 60601",
    profilePicture: undefined,
    role: { id: "role-admin", name: "Admin" },
    isActive: true,
    createdAt: "2024-01-01T10:00:00Z",
    lastLoginAt: "2024-12-13T09:00:00Z",
  },
]

// ===== MOCK DOCTORS =====
export const mockDoctors: DoctorProfileViewModel[] = [
  {
    doctorId: "doc-1",
    userId: "doctor-456",
    fullName: "Dr. Sarah Smith",
    email: "dr.smith@email.com",
    phoneNumber: "+1987654321",
    specialization: "Cardiology",
    qualifications: "MD, FACC, Board Certified Cardiologist",
    professionalTitle: "Cardiologist & Heart Disease Specialist",
    experience: 15,
    licenseNumber: "MD12345",
    licenseState: "Massachusetts",
    licenseIssueDate: "2009-06-15",
    licenseExpiryDate: "2029-06-15",
    npiNumber: "1234567890",
    isVerified: true,
    consultationFee: 150,
    bio: "Experienced cardiologist with 15 years of practice specializing in heart disease prevention and treatment. I am passionate about helping patients maintain healthy hearts through personalized care plans and cutting-edge treatment approaches. My practice focuses on preventive cardiology, interventional procedures, and comprehensive cardiac care.",
    address: "456 Medical Plaza, Boston, MA 02101",
    educationTraining: "Doctor of Medicine - Harvard Medical School (2001-2005)\nInternal Medicine Residency - Massachusetts General Hospital (2005-2008) | Internal Medicine\nCardiology Fellowship - Johns Hopkins Hospital (2008-2011) | Cardiology",
    boardCertifications: "Board Certified in Cardiology - American Board of Internal Medicine | Certified June 15, 2011, Expires June 15, 2026\nAdvanced Cardiac Life Support (ACLS) - American Heart Association | Certified March 10, 2020, Expires March 10, 2025",
    profilePicture: undefined,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    availableTimeStart: "09:00",
    availableTimeEnd: "17:00",
    averageRating: 4.8,
    totalReviews: 127,
    totalPatients: 450,
    completedConsultations: 890,
    recentReviews: [],
  },
  {
    doctorId: "doc-2",
    userId: "doctor-789",
    fullName: "Dr. Michael Chen",
    email: "dr.chen@email.com",
    phoneNumber: "+1555666777",
    specialization: "Dermatology",
    qualifications: "MD, Board Certified Dermatologist",
    professionalTitle: "Dermatologist & Cosmetic Specialist",
    experience: 10,
    licenseNumber: "MD67890",
    licenseState: "California",
    licenseIssueDate: "2014-08-20",
    licenseExpiryDate: "2034-08-20",
    npiNumber: "9876543210",
    isVerified: true,
    consultationFee: 120,
    bio: "Specialized in skin conditions, acne treatment, and cosmetic dermatology. My goal is to help patients achieve healthy, beautiful skin through evidence-based treatments and personalized skincare plans. I stay current with the latest advances in dermatology to provide the best care possible.",
    address: "789 Derma Center, San Francisco, CA 94102",
    educationTraining: "Doctor of Medicine - Stanford University School of Medicine (2006-2010)\nDermatology Residency - UCSF Medical Center (2010-2013) | Dermatology",
    boardCertifications: "Board Certified in Dermatology - American Board of Dermatology | Certified August 20, 2014, Expires August 20, 2024\nCosmetic Dermatology Certification - American Academy of Cosmetic Surgery | Certified January 15, 2016, Expires January 15, 2026",
    profilePicture: undefined,
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableTimeStart: "10:00",
    availableTimeEnd: "18:00",
    averageRating: 4.6,
    totalReviews: 98,
    totalPatients: 320,
    completedConsultations: 650,
    recentReviews: [],
  },
  {
    doctorId: "doc-3",
    userId: "doctor-101",
    fullName: "Dr. Emily Johnson",
    email: "dr.johnson@email.com",
    phoneNumber: "+1777888999",
    specialization: "Pediatrics",
    qualifications: "MD, Board Certified Pediatrician",
    professionalTitle: "Pediatrician & Child Healthcare Specialist",
    experience: 12,
    licenseNumber: "MD11111",
    licenseState: "Washington",
    licenseIssueDate: "2012-05-10",
    licenseExpiryDate: "2032-05-10",
    npiNumber: "5551234567",
    isVerified: true,
    consultationFee: 100,
    bio: "Dedicated pediatrician caring for children from infancy through adolescence. I believe in building strong relationships with families and providing compassionate, comprehensive care that supports healthy development. My practice emphasizes preventive care, early intervention, and family-centered treatment approaches.",
    address: "321 Children's Health, Seattle, WA 98101",
    educationTraining: "Doctor of Medicine - University of Washington School of Medicine (2004-2008)\nPediatrics Residency - Seattle Children's Hospital (2008-2011) | Pediatrics\nDevelopmental Pediatrics Fellowship - Boston Children's Hospital (2011-2012) | Developmental Pediatrics",
    boardCertifications: "Board Certified in Pediatrics - American Board of Pediatrics | Certified May 10, 2012, Expires May 10, 2029\nPediatric Advanced Life Support (PALS) - American Heart Association | Certified September 5, 2022, Expires September 5, 2025",
    profilePicture: undefined,
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    availableTimeStart: "08:00",
    availableTimeEnd: "16:00",
    averageRating: 4.9,
    totalReviews: 156,
    totalPatients: 680,
    completedConsultations: 1200,
    recentReviews: [],
  },
]

// ===== MOCK APPOINTMENTS =====
export const mockAppointments: AppointmentItemViewModel[] = [
  {
    appointmentId: "apt-1",
    patientName: "John Doe",
    doctorName: "Dr. Sarah Smith",
    doctorId: "doc-1",
    doctorSpecialization: "Cardiology",
    doctorProfilePicture: undefined,
    appointmentDate: "2024-12-20T10:00:00Z",
    timeSlot: "10:00 AM",
    durationMinutes: 30,
    status: "Scheduled",
    reasonForVisit: "Chest pain and irregular heartbeat",
    consultationFee: 150,
    confirmationNumber: "CONF-001-2024",
  },
  {
    appointmentId: "apt-2",
    patientName: "John Doe",
    doctorName: "Dr. Michael Chen",
    doctorId: "doc-2",
    doctorSpecialization: "Dermatology",
    doctorProfilePicture: undefined,
    appointmentDate: "2024-12-15T14:00:00Z",
    timeSlot: "02:00 PM",
    durationMinutes: 30,
    status: "Completed",
    reasonForVisit: "Skin rash evaluation",
    consultationFee: 120,
    confirmationNumber: "CONF-002-2024",
  },
]

// ===== MOCK CONSULTATIONS =====
export const mockConsultations: ConsultationViewModel[] = [
  {
    appointmentId: "apt-2",
    appointmentDate: "2024-12-15T14:00:00Z",
    patientName: "John Doe",
    reasonForVisit: "Skin rash evaluation",
    appointmentNotes: "Patient reported itching and redness",
    patientId: "patient-123",
    patientGender: "Male",
    patientDateOfBirth: "1985-05-15",
    patientPhone: "+1234567890",
    patientEmail: "john.doe@email.com",
    patientMedicalHistory: "No significant medical history",
    patientAllergies: "Penicillin",
    aiPrediction: undefined,
    officialDiagnosis: "Contact Dermatitis",
    aiDiagnosisConfirmed: false,
    consultationNotes: "Patient presents with localized rash on forearm. Appears to be allergic reaction.",
    treatmentPlan: "Topical corticosteroid cream, avoid irritants",
    labTestsOrdered: "None",
    labReports: "",
    specialistReferrals: "",
    patientRecordNotes: "",
    followUpRequired: true,
    followUpDate: "2024-12-29T14:00:00Z",
    followUpInstructions: "Return if rash persists after 2 weeks",
    prescriptions: [
      {
        id: "rx-1",
        drugName: "Hydrocortisone Cream 1%",
        dosage: "Apply thin layer",
        frequency: "Twice daily",
        duration: "14 days",
        instructions: "Apply to affected area, avoid contact with eyes",
      },
    ],
    isCompleted: true,
    completedDate: "2024-12-15T14:30:00Z",
    consultationRecordId: "consult-1",
    doctorName: "Dr. Michael Chen",
    doctorSpecialization: "Dermatology",
  },
]

// ===== MOCK PREDICTIONS =====
export const mockPredictions: PredictionResultViewModel[] = [
  {
    id: 1,
    predictionId: "pred-001",
    timestamp: "2024-12-10T15:30:00Z",
    createdAt: "2024-12-10T15:30:00Z",
    primaryDisease: "Hypertension",
    predictedDisease: "Hypertension",
    primaryConfidence: 78.5,
    confidenceScore: 78.5,
    symptomsCount: 5,
    urgencyLevel: "Medium",
    allProbabilities: [
      { diseaseName: "Hypertension", probability: 78.5 },
      { diseaseName: "Cardiac Arrhythmia", probability: 12.3 },
      { diseaseName: "Anxiety Disorder", probability: 5.2 },
      { diseaseName: "Hyperthyroidism", probability: 4.0 },
    ],
    probabilityBreakdown: [
      { diseaseName: "Hypertension", probability: 78.5 },
      { diseaseName: "Cardiac Arrhythmia", probability: 12.3 },
      { diseaseName: "Anxiety Disorder", probability: 5.2 },
      { diseaseName: "Hyperthyroidism", probability: 4.0 },
    ],
    inputSummary: {
      age: 39,
      sex: 1,
      chestPainType: 2,
      restingBloodPressure: 145,
      serumCholesterol: 220,
      fastingBloodSugar: 1,
      restingECG: 0,
      maxHeartRate: 150,
      exerciseInducedAngina: 0,
      stDepression: 1.2,
      slopeOfPeakExercise: 1,
      numberOfMajorVessels: 0,
      thalassemia: 2,
      cough: 0,
      shortnessOfBreath: 1,
      wheezing: 0,
      fever: 0,
      fatigue: 1,
      headache: 1,
      nauseaVomiting: 0,
      abdominalPain: 0,
      diarrhea: 0,
      lossOfAppetite: 0,
      submittedAt: "2024-12-10T15:30:00Z",
    },
    recommendations: [
      "Consult a cardiologist for proper evaluation",
      "Monitor blood pressure regularly",
      "Adopt a heart-healthy diet low in sodium",
      "Engage in regular physical activity",
      "Consider stress management techniques",
    ],
    disclaimerMessage:
      "This AI prediction is for informational purposes only and should not replace professional medical advice.",
    disclaimer:
      "This AI prediction is for informational purposes only and should not replace professional medical advice.",
  },
]

// ===== MOCK ADMIN STATISTICS =====
export const mockAdminStats: SystemStatistics = {
  totalPatients: 1250,
  totalDoctors: 45,
  totalAppointments: 3420,
  totalPredictions: 2150,
  activePatients: 890,
  verifiedDoctors: 42,
  upcomingAppointments: 156,
  todayAppointments: 23,
  pendingDoctorApprovals: 3,
  pendingAppointmentCancellations: 5,
  totalRevenue: 485000,
  monthlyRevenue: 45000,
  patientGrowthRate: 12.5,
  doctorGrowthRate: 8.3,
  appointmentGrowthRate: 15.7,
  revenueGrowthRate: 18.2,
}

// ===== MOCK PENDING DOCTORS =====
export const mockPendingDoctors: DoctorApprovalViewModel[] = [
  {
    doctorId: "doc-pending-1",
    userId: "user-pending-1",
    firstName: "Robert",
    lastName: "Williams",
    email: "dr.williams@email.com",
    phoneNumber: "+1234567890",
    specialization: "Orthopedics",
    licenseNumber: "MD99999",
    hospitalAffiliation: "City General Hospital",
    yearsOfExperience: 8,
    educationDetails: "MD from Johns Hopkins, Orthopedic Surgery Residency",
    createdAt: "2024-12-01T10:00:00Z",
  },
]

// ===== MOCK PATIENT PROFILE =====
export const mockPatientProfile: PatientProfileSummaryViewModel = {
  patientId: "pat-1",
  userId: "patient-123",
  firstName: "John",
  lastName: "Doe",
  email: "john.doe@email.com",
  phoneNumber: "+1234567890",
  dateOfBirth: "1985-05-15",
  gender: "Male",
  address: "123 Main St, New York, NY 10001",
  bloodType: "A+",
  allergies: "Penicillin",
  medicalHistory: "No significant medical history",
  profilePicture: undefined,
  createdAt: "2024-01-15T10:00:00Z",
}
